name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.2', '7.3']

    steps:
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer Directory
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: php-${{ matrix.php-version }}-composer-dev-${{ hashFiles('composer.lock') }}
          restore-keys: php-${{ matrix.php-version }}-composer-dev-

      - name: Composer install (with dev)
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run phplint
        run: composer run-script phplint

      - name: Run phpcs
        run: composer run-script phpcs

      - name: Run phpstan
        run: composer run-script phpstan

      - name: Run phpunit
        run: composer run-script phpunit
